### ISSUE TITLE
Copy Last Building [B] stops working

### ISSUE THREAD

**Issue by chip-nerd** [llunak/oni-deliverytemperaturelimit#1]
Hotkey [B] for Copy Last Building stops working for buildings in progress (which are not built yet). Hotkey [B] still works for copying completed buildings.

**Comment by llunak** [comment]
I cannot reproduce. If I place a blueprint for e.g. a tile, I can select it, hit 'B' and place another tile.

**Comment by chip-nerd** [comment]
Thanks for checking! I'll check if its interference of other mods.
